version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    restart: always
    container_name: mi-learning-db
    env_file:
      - ./env/prod.env
    ports:
      - 5433:5432
      - 5432:5432

  auth:
    build: 
      context: .
      dockerfile: ./docker/auth/Dockerfile
    restart: always
    container_name: mi-learning-auth
    env_file: 
      - ./env/prod.env
    depends_on:
      - db
    ports:
      - 8000:80
    expose:
      - 80
    links:
      - db

  app:
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: app
    container_name: mi-learning-app
    profiles:
      - prod
    env_file:
      - ./env/prod.env
    environment:
      - ENV=dev
    depends_on:
      - db
      - auth
    ports:
      - 8080:8080
    links: 
      - db
      - auth
    restart: on-failure 