version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    restart: always
    container_name: mi-learning-db
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5433:5432
      - 5432:5432

  auth:
    build: 
      context: .
      dockerfile: ./docker/auth/Dockerfile
    restart: always
    container_name: mi-learning-auth
    profiles:
      - prod
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SECRET_KEY
      - ALGORITHM
    depends_on:
      - db
    ports:
      - 8000:80
    links:
      - db
    expose:
      - 80

  app:
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: mi-learning-app
    profiles:
      - prod
    environment:
      - ENV=dev
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - AUTH_HOST
      - AUTH_PORT
    links:
      - db
      - auth
    depends_on:
      - db
      - auth
    ports:
      - 8080:8080
    restart: on-failure