version: '3'

services:
  db:
    image: postgres
    container_name: mi-learning-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mi_learning