version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    restart: always
    container_name: mi-learning-db
    env_file:
      - ./env/dev.env
    ports:
      - 5433:5432

  auth:
    build: 
      context: .
      dockerfile: ./docker/auth/Dockerfile
    restart: always
    container_name: mi-learning-auth
    env_file: 
      - ./env/dev.env
    depends_on:
      - db
    ports:
      - 8000:80
      
      


