version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    restart: always
    container_name: mi-learning-db
    env_file:
      - ./env/dev.env
    ports:
      - 5433:5432
