version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    restart: always
    container_name: mi-learning-db
    env_file:
      - ./env/dev.env
    ports:
      - 5433:5432
      - 5432:5432

  auth:
    build: 
      context: .
      dockerfile: ./docker/auth/Dockerfile
    restart: always
    container_name: mi-learning-auth
    env_file: 
      - ./env/dev.env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
    ports:
      - 8000:80
    links:
      - db

  # app:
  #   build: 
  #     context: .
  #     dockerfile: ./docker/app/Dockerfile
  #   image: app
  #   container_name: mi-learning-app
  #   env_file:
  #     - "./env/dev.env"
  #   environment:
  #     - POSTGRES_HOST=db
  #     - AUTH_HOST=auth
  #   depends_on:
  #     - auth
  #   ports:
  #     - 8080:3000
  #   links: 
  #     - db
  #     - auth
  #   restart: on-failure 